apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin-secret
  namespace: cephfs
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: QVFEZHRzWmFXYkJVT2hBQWJhRTVIQzBwaEhqeUYrczdhbFJHcEE9PQ==
--- 
apiVersion: v1
kind: Secret
metadata:
  name: ceph-admin-secret
type: "kubernetes.io/rbd"
data:
  # ceph auth get-key client.admin | base64
  key: QVFEZHRzWmFXYkJVT2hBQWJhRTVIQzBwaEhqeUYrczdhbFJHcEE9PQ==

