apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    app: filebeat
spec:
  template:
    metadata:
      labels:
        app: filebeat
      name: filebeat
    spec:
      containers:
      - name: filebeat
        image: docker.elastic.co/flibeat/filebeat:latest
        imagePullPolicy: Always
#         resources:
#           limits:
#             cpu: 100m
#             memory: 100Mi
        env:
          - name: REDIS
            value: redis-es:6379
          - name: LOG_LEVEL
            value: info
          - name: VAULT_ADDR
            value: http://vault.default:8200
          - name: ENVIRONMENT
            valueFrom:
              configMapKeyRef:
                name: env-config
                key: environment
        volumeMounts:
        - name: varlog
          mountPath: /LOGS/varlog
        - name: socket
          mountPath: /var/run/docker.sock
        - name: logs
          mountPath: /LOGS
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: socket
        hostPath:
          path: /var/run/docker.sock
      # Application non-stdout logs
      - name: logs
        hostPath:
          path: /LOGS
