apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
  namespace: kube-system
  labels:
    app: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: es
        image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
        command: ["bin/elasticsearch"]
        args: ["-Expack.security.enabled=false"]
#         args: ["-Expack.security.enabled=false", "-Ebootstrap.memory_lock=true"]
        env:
        - name: "CLUSTER_NAME"
          value: "logs-cluster"
        - name: ES_JAVA_OPTS
          value: "-Xms512m -Xmx512m"
        ports:
        - containerPort: 9200
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /data
          name: storage
      volumes:
      - name: storage
        emptyDir: {}
