apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    name: node-exporter
  name: node-exporter
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: node-exporter
      annotations:
        prometheus.io/port: "9100"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: node-exporter
        image: "quay.io/prometheus/node-exporter"
        ports:
          - containerPort: 9100
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /host/proc
            name: proc-fs
          - mountPath: /host/sys
            name: sys-fs
          - mountPath: /rootfs
            name: root-fs
      hostNetwork: true
      hostPID: true
      volumes:
          - name: proc-fs
            hostPath:
              path: /proc
          - name: sys-fs
            hostPath:
              path: /sys
          - name: root-fs
            hostPath:
              path: /
